[custom.ros_ws]
command = "printf %s \"$ROS_WS_NAME\""
when    = '[[ -n "$ROS_WS_NAME" ]]'
format  = " [$output]($style)"
style   = "bright-blue"
[conda]
symbol = "🅒 "
style = "green"
ignore_base = false
